# Docker
# BuildAndPush a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: BuildAndPush image
  jobs:
  - job: BuildAndPush
    displayName: BuildAndPush
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: BuildAndPush an image
      inputs:
        containerRegistry: '<project_id>'
        repository: '<project_id>/<project-statement>'
        tags: 'v0.27.2'
        command: buildAndPush
        dockerfile: '<path until docker file>/Dockerfile'
